import type { News } from '../type';

const news: News[] = [
  {
    id: '728ed52f',
    slug: 'slug123',
    alt: 'alt123',
    imageUrl: '/',
    formattedHeadline: 'Headline123',
    formattedDescription: 'description123',
    formattedAlt: 'alt123',
    date: new Date('2024/03/29'),
    isDeleted: false,
    createdAt: new Date('2024/03/29'),
    updatedAt: new Date('2024/03/29'),
    headline: '1',
    description: ' 100',
    status: 'draft',
  },
  {
    id: '728ed52g',
    slug: 'slug123',
    alt: 'alt123',
    imageUrl: '/',
    formattedHeadline: 'Headline123',
    formattedDescription: 'description123',
    formattedAlt: 'alt123',
    date: new Date(),
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    headline: 'Headline123',
    description: ' 200',
    status: 'processing',
  },
  {
    id: '728ed52h',
    slug: 'slug123',
    alt: 'alt123',
    imageUrl: '/',
    formattedHeadline: 'Headline123',
    formattedDescription: 'description123',
    formattedAlt: 'alt123',
    date: new Date(),
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    headline: 'Headline123',
    description: ' 300',
    status: 'published',
  },
  {
    id: '728ed52i',
    slug: 'slug123',
    alt: 'alt123',
    imageUrl: '/',
    formattedHeadline: 'Headline123',
    formattedDescription: 'description123',
    formattedAlt: 'alt123',
    date: new Date(),
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    headline: 'Headline123',
    description: ' 400',
    status: 'failed',
  },
  {
    id: '728ed52j',
    slug: 'slug123',
    alt: 'alt123',
    imageUrl: '/',
    formattedHeadline: 'Headline123',
    formattedDescription: 'description123',
    formattedAlt: 'alt123',
    date: new Date(),
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    headline: 'Headline123',
    description: ' 500',
    status: 'archived',
  },
  {
    id: '728ed52k',
    slug: 'slug123',
    alt: 'alt123',
    imageUrl: '/',
    formattedHeadline: 'Headline123',
    formattedDescription: 'description123',
    formattedAlt: 'alt123',
    date: new Date(),
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    headline: 'Headline123',
    description: ' 600',
    status: 'processing',
  },
  {
    id: '728ed52l',
    slug: 'slug123',
    alt: 'alt123',
    imageUrl: '/',
    formattedHeadline: 'Headline123',
    formattedDescription: 'description123',
    formattedAlt: 'alt123',
    date: new Date(),
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    headline: 'Headline123',
    description: ' 700',
    status: 'published',
  },
  {
    id: '728ed52m',
    slug: 'slug123',
    alt: 'alt123',
    imageUrl: '/',
    formattedHeadline: 'Headline123',
    formattedDescription: 'description123',
    formattedAlt: 'alt123',
    date: new Date(),
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    headline: 'Headline123',
    description: ' 800',
    status: 'failed',
  },
  {
    id: '728ed52n',
    slug: 'slug123',
    alt: 'alt123',
    imageUrl: '/',
    formattedHeadline: 'Headline123',
    formattedDescription: 'description123',
    formattedAlt: 'alt123',
    date: new Date(),
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    headline: 'Headline123',
    description: ' 900',
    status: 'draft',
  },
  {
    id: '728ed52o',
    slug: 'slug123',
    alt: 'alt123',
    imageUrl: '/',
    formattedHeadline: 'Headline123',
    formattedDescription: 'description123',
    formattedAlt: 'alt123',
    date: new Date(),
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    headline: 'Headline123',
    description: ' 1000',
    status: 'processing',
  },
  {
    id: '728ed52p',
    slug: 'slug123',
    alt: 'alt123',
    imageUrl: '/',
    formattedHeadline: 'Headline123',
    formattedDescription: 'description123',
    formattedAlt: 'alt123',
    date: new Date(),
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    headline: 'Headline123',
    description: ' 1100',
    status: 'published',
  },
];

export async function getNews(newsId: string) {
  return news.find((item) => item.id === newsId);
}
